### ISSUE TITLE
RECORD not declared in RECORD

### ISSUE THREAD

**Issue by jwodder** [repo-helper/whey#14]
Seemingly all of the projects built with whey — aside from whey itself, for some reason — omit the entry for `*.dist-info/RECORD` from the `RECORD` file.  This has been observed on the following packages (links are to Wheelodex.org, which reports the irregularity at the top of the page):
* [toctree-plus](https://www.wheelodex.org/projects/toctree-plus/)
* [astatine](https://www.wheelodex.org/projects/astatine/)
* [sphinx-toolbox](https://www.wheelodex.org/projects/sphinx-toolbox/)
* [emoji-strings](https://www.wheelodex.org/projects/emoji-strings/)
* [flake8-strftime](https://www.wheelodex.org/projects/flake8-strftime/)
* [flake8-sphinx-links](https://www.wheelodex.org/projects/flake8-sphinx-links/)
* [flake8-slots](https://www.wheelodex.org/projects/flake8-slots/)

(I stopped checking at this point, but I think you get the idea.)

Now, while PEP 427 is not 100% clear on whether `RECORD` needs to be listed in `RECORD`, my reading is that it does need to be in there, and the fact that [the `RECORD` in whey itself](https://www.wheelodex.org/projects/whey/#record) lists `RECORD` implies that including it is the intended behavior for whey.

**Comment by domdfcoding** [comment]
When I first read PEP 427 I interpreted it as meaning RECORD doesn't include an entry for itself, but re-reading it I think you're correct that it should be included, just without the hash.

Thanks for letting me me know. This should be fixed now.
